version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app/app.py
      - SECRET_KEY=${SECRET_KEY}
      - FLAG=practice{session_fixation_worked}
    volumes:
      - .:/app
